### ISSUE TITLE
I was not able to run training code

### ISSUE THREAD

**Issue by alexander-malafeev** [microsoft/Deep3DFaceReconstruction#111]
Dear Dr. Deng, 

I was trying to run training code but it crashed with the segmentation fault.
I downloaded the binary of the renderer, BFM and pretrained networks as was indicated in the instruction.
In order to get tensorflow 1.12 I used docker image tensorflow/tensorflow:1.12.0-gpu-py3
the version of CUDA inside the docker is 9.0. The GPU is 2080ti.
Perhaps you could indicate the direction where I should look for the cause of the segfault?

**Comment by YuDeng** [comment]
Hi, did you successfully run the test code (demo.py)?

**Comment by alexander-malafeev** [comment]
Thanks for the quick reply!
Yes, I was able to run demo code both with docker and conda environment (the difference would be cuda version) using cpu.
However neither configuration was able to run demo on gpu.

I was able to run demo with newer version of tensorflow using compatibility with tensorflow 1.
Unfortunately it is not possible to do for training code because of the tf_mesh_renderer.

If I use conda environment with tf 1.12.0 and cuda 10.1 then the training code crashes with another error:
"TypeError: input 'filename' or 'ReadFile' Op has type float32 that does not match expected type of string."

**Comment by YuDeng** [comment]
Hi, there are two ways to successfully run the training code in conda environment.

First, install the tensorflow via pip install tensorflow-gpu==1.12.0, and you have to make sure that the cuda in /usr/local/cuda is link to cuda-9.0. In this way, you should be able to use the pre-compiled binary file (rasterize_triangles_kernel.so) provided in this repository.

Second, you can install tensorflow via conda install tensorflow==1.12.0. In this way, you don't have to link /usr/local/cuda to cuda-9.0 explicitly because conda will install all dependencies automatically. If you install tensorflow using conda, then you cannot directly use the pre-compiled binary in this repository. You have to compile tf_mesh_renderer by yourself via the following steps:
1. git clone https://github.com/google/tf_mesh_renderer.git
2. git checkout ba27ea1798 (our code builds on an older version of tf mesh renderer)
3. replace the content in ./WORKSPACE with:
workspace(name = "tf_mesh_renderer")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# GoogleTest/GoogleMock framework. Used by most unit-tests.
http_archive(
     name = "com_google_googletest",
     urls = ["https://github.com/google/googletest/archive/master.zip"],
     strip_prefix = "googletest-master",
)
4. replace "$(PYTHON)" with "python" at line 27, 28 in ./mesh_renderer/kernels/BUILD, and set -D_GLIBCXX_USE_CXX11_ABI=0 to -D_GLIBCXX_USE_CXX11_ABI=1 at line 29.
5. run bazel test ... in the terminal
After all these steps, you should be able to get rasterize_triangles_kernel.so in bazel-bin/mesh_renderer/kernels. Copy it to the specified folder following the instruction of our repository. Finally, you should be able to run train.py.

Note that rasterize_triangles_kernel.so can only be run using CPU. Therefore, if you specify the tf.device to /gpu:0 for all Ops in the graph, errors would occur. You can either run the code without setting tf.device or add "with  tf.device('/cpu:0'):" before the rendering Op.

Let me know if you can run the training code in these ways.

**Comment by alexander-malafeev** [comment]
Thank you for the reply!
The reason for the type error was that I did not provide the path for validation data.
Now I was able to run training code in conda environment!

**Comment by fisakhan** [comment]
@alexander-malafeev how did you run demo.py with newer version of tensorflow using compatibility with tensorflow 1. How did you use the pre-compiled binary file (rasterize_triangles_kernel.so) with newer version of tensorflow >= 2? Please have a look at https://github.com/microsoft/Deep3DFaceReconstruction/issues/157 . Can you please help?
