### ISSUE TITLE
Genova et al result

### ISSUE THREAD

**Issue by mwolff31** [microsoft/Deep3DFaceReconstruction#23]
Hi! Thank you for open sourcing your code! I noticed in your paper that you reported Genova et al's average RMSE result on MICC to be ~1.78, however, Genova et al report (what i assume to be the same evaluation metric) to be ~1.50...is there a reason for this?

**Comment by YuDeng** [comment]
Hi, we do not use the same evaluation metric as in Genova's paper. our evaluation protocol are slightly different to theirs.
1.In their protocol, they first estimate a global scaling factor between their model (Basel2017 Model) and [51]’s , then they do ICP alignment with ground truth meshes and calculate point-to-plane distance; For us, we do SICP for each mesh so that the scaling factor for each reconstruction result is unique compare to Genova’s single global scaling factor.
2.When calculate point-to-plane distance after doing ICP, they seem to calculate distance lies only in the intersection region as is described in their paper. But how they determine the intersection region is unknown because the evaluation code they provide to us is a .exe file. While in our protocol, we calculate the distance for each vertex lies in 95mm radius around the nose tip of ground truth mesh (We also cut the forehead region as mentioned in the paper). 
3.We compute an RMSE across vertex for each mesh and we infer that they calculate a mean error. 
As a result, their evaluation metric is not quite clear to us so we decide to use our own evaluation method in our paper. We get the reconstruction meshes of [16] and [51] on MICC from Genova, and use our evaluation protocol to get the table 2 in our paper.
Thanks.

**Comment by mwolff31** [comment]
thanks!

**Comment by DragonZzzz** [comment]
@YuDeng  It is convenient to share the reconstrucion meshes of [16] and [51] and the evaluation code on MICC from Genova? I'm a little confused about the evaluation metric in different papers? Thank you~ m15308260580@163.com

**Comment by Xudong7Chen** [comment]
Can you share me with the reconstrucion meshes of [16] and [51] and the evaluation code on MICC from Genova? Thank you. Email: xudong7chen@gmail.com

**Comment by sbyNiceBlowJob** [comment]
How to calculate the point-to-plane distance for each vertex?  Can you explain more detailed please?

**Comment by acmlau** [comment]
I am also interested in the evaluation code. Email: [anna.lau@student.uva.nl](mailto:anna.lau@student.uva.nl)
