### ISSUE TITLE
Can I use 68 landmarks instead of ?

### ISSUE THREAD

**Issue by DavisDDD** [microsoft/Deep3DFaceReconstruction#66]
I have a txt of 68 landmarks. But in program, it need five landmarks. How can I use landmark instead?

**Comment by umarmuzammil** [comment]
I am also trying to use 68 landmarks. Did you figure it out ?

**Comment by YuDeng** [comment]
The 5 landmarks we use are located at the center of right eye, the center of left eye, nose tip, right corner of mouth, and left corner of mouth respectively. You can transfer 68 landmarks to 5 accordingly.

**Comment by umarmuzammil** [comment]
yeah for 5 landmarks I am using this  "shape_predictor_5_face_landmarks"  available for dlib library but I've no idea how to make "shape_predictor_68_face_landmarks"  work. there is no example in input folder for 68 marks.  Does seem to work as expected when you generate 68 landmarks text doc instead of 5.

**Comment by Timmate** [comment]
> The 5 landmarks we use are located at the center of right eye, the center of left eye, nose tip, right corner of mouth, and left corner of mouth respectively. You can transfer 68 landmarks to 5 accordingly.

@YuDeng, it would be nice if you could post that information right on the project's page so that people could find it more easily.
